#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kendo.Component.AdvancedSort.Mvc
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using FirstStrike.Retail.Web.KendoComponent.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/AdvancedSort/_AdvancedSortModal.cshtml")]
    public partial class _Views_AdvancedSort__AdvancedSortModal_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_AdvancedSort__AdvancedSortModal_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(" id=\"sort-criteria-validation-msg\"");

WriteLiteral("></div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"sort-message\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"k-icon k-i-info\"");

WriteLiteral("></span>&nbsp;<span");

WriteLiteral(" id=\"message\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" class=\"k-button-primary\"");

WriteLiteral(" id=\"applyAdvancedSort\"");

WriteLiteral(" title=\"Apply Sort\"");

WriteLiteral("><span");

WriteLiteral(" class=\"k-icon k-i-check\"");

WriteLiteral("></span>Apply Sort</button>\r\n            <button");

WriteLiteral(" class=\"k-button-primary\"");

WriteLiteral(" id=\"resetAdvancedSort\"");

WriteLiteral(" disabled");

WriteLiteral(" title=\"Reset to Previous State\"");

WriteLiteral("><span");

WriteLiteral(" class=\"k-icon k-i-reset\"");

WriteLiteral("></span>Reset</button>\r\n            <button");

WriteLiteral(" class=\"k-button-primary\"");

WriteLiteral(" id=\"clearAdvancedSort\"");

WriteLiteral(" title=\"Clear Sort Columns\"");

WriteLiteral("><span");

WriteLiteral(" class=\"k-icon k-i-cancel\"");

WriteLiteral("></span>Clear</button>\r\n        </div>\r\n        <div");

WriteLiteral(" style=\"clear:both\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" id=\"sort-criteria\"");

WriteLiteral(" role=\"application\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"sort-criteria-section k-content wide\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"sort-criteria-header\"");

WriteLiteral(" for=\"available\"");

WriteLiteral(" id=\"sortcolumns\"");

WriteLiteral(">Available Columns</label>\r\n                <label");

WriteLiteral(" class=\"sort-criteria-header\"");

WriteLiteral(" for=\"selected\"");

WriteLiteral(">Sort Columns</label>\r\n                <br />\r\n                <select");

WriteLiteral(" data-role=\"listbox\"");

WriteLiteral(" id=\"advanced-sort-available\"");

WriteLiteral(" name=\"advanced-sort-available\"");

WriteLiteral("></select>\r\n                <select");

WriteLiteral(" data-role=\"listbox\"");

WriteLiteral(" id=\"advanced-sort-selected\"");

WriteLiteral(" name=\"advanced-sort-selected\"");

WriteLiteral("></select>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n<script");

WriteLiteral(" id=\"selected-sort-column-template\"");

WriteLiteral(" type=\"text/x-kendo-template\"");

WriteLiteral(@">
    #: data.columnName #
    <div class=""pull-right"">
        <div class=""advanced-sort-order"" id=""advanced-sort-order-#: data.columnValue #"">
            <span data-icon=""sort-asc"" title=""Ascending""></span>
            <span data-icon=""sort-desc"" title=""Descending""></span>
        </div>
    </div>
</script>");

        }
    }
}
#pragma warning restore 1591
